#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright 2025 Michael van der Westhuizen
#

#
#	Global definitions for armv8 sbbr implementation specific modules.
#

#
#	Define directories.
#
ROOT_SBBR_DIR		= $(ROOT_PLAT_DIR)/ARMH,sbbr
ROOT_SBBR_MOD_DIR	= $(ROOT_SBBR_DIR)/kernel
ROOT_SBBR_MISC_DIR_32	= $(ROOT_SBBR_DIR)/kernel/misc
ROOT_SBBR_MISC_DIR_64	= $(ROOT_SBBR_MISC_DIR_32)/$(SUBDIR64)
ROOT_SBBR_KERN_DIR_32	= $(ROOT_SBBR_MOD_DIR)
ROOT_SBBR_KERN_DIR_64	= $(ROOT_SBBR_MOD_DIR)/$(SUBDIR64)
ROOT_SBBR_DRV_DIR_32	= $(ROOT_SBBR_MOD_DIR)/drv
ROOT_SBBR_DRV_DIR_64	= $(ROOT_SBBR_MOD_DIR)/drv/$(SUBDIR64)

ROOT_SBBR_KERN_DIR	= $(ROOT_SBBR_KERN_DIR_$(CLASS))
ROOT_SBBR_DRV_DIR	= $(ROOT_SBBR_DRV_DIR_$(CLASS))
ROOT_SBBR_MISC_DIR	= $(ROOT_SBBR_MISC_DIR_$(CLASS))

ROOT_PLAT_MOD_DIRS      += $(ROOT_SBBR_MOD_DIR)
ROOT_PLAT_MISC_DIRS     += $(ROOT_SBBR_MISC_DIR)

ROOT_SBBR_LIB_DIR	= $(ROOT_SBBR_DIR)/lib

USR_ARMV8_PLAT_DIR	= $(USR_PLAT_DIR)/$(PLATFORM)
USR_SBBR_DIR		= $(USR_PLAT_DIR)/ARMH,sbbr
USR_SBBR_SBIN_DIR	= $(USR_SBBR_DIR)/sbin
USR_SBBR_INC_DIR	= $(USR_SBBR_DIR)/include
USR_SBBR_LIB_DIR	= $(USR_SBBR_DIR)/lib
USR_SBBR_ISYS_DIR	= $(USR_SBBR_INC_DIR)/sys

#
#	Define modules.
#
SBBR_KMODS = platmod cpudrv

#
#	Include the makefiles which define build rule templates, the
#	collection of files per module, and a few specific flags. Note
#	that order is significant, just as with an include path. The
#	first build rule template which matches the files name will be
#	used. By including these in order from most machine dependent
#	to most machine independent, we allow a machine dependent file
#	to be used in preference over a machine independent version
#	(Such as a machine specific optimization, which preserves the
#	interfaces.)
#

include $(UTSBASE)/armv8/sbbr/Makefile.files
#
#	Include common rules.
#
include $(UTSBASE)/armv8/Makefile.armv8

UNIX_DIR  = $(UTSBASE)/armv8/sbbr/unix
# UNIX_O = $(UNIX_DIR)/$(OBJS_DIR)/unix.o
MODSTUBS_DIR = $(UNIX_DIR)


#
#	Define the actual specific platforms
MACHINE_DEFS	+= -D$(PLATFORM) -D_MACHDEP
