#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright 2017 Hayashi Naoyuki
# Copyright 2025 Michael van der Westhuizen
#
#	Common targets for armv8 sbbr platform-implementation specific modules.
#

.KEEP_STATE:

#
# Rules for implementation subdirectories.
#
$(ROOT_SBBR_DIR): $(ROOT_PLAT_DIR)
	-$(INS.dir)

$(ROOT_SBBR_MOD_DIR): $(ROOT_SBBR_DIR)
	-$(INS.dir)

# ROOT_SBBR_KERN_DIR_32 and ROOT_SBBR_MOD_DIR are the same

$(ROOT_SBBR_KERN_DIR_64): $(ROOT_SBBR_MOD_DIR)
	-$(INS.dir)

$(ROOT_SBBR_DRV_DIR_32): $(ROOT_SBBR_MOD_DIR)
	-$(INS.dir)

$(ROOT_SBBR_DRV_DIR_64): $(ROOT_SBBR_DRV_DIR_32)
	-$(INS.dir)

$(ROOT_SBBR_LIB_DIR): $(ROOT_SBBR_DIR)
	-$(INS.slink2)

$(ROOT_SBBR_MISC_DIR_32): $(ROOT_SBBR_MOD_DIR)
	-$(INS.dir)

$(ROOT_SBBR_MISC_DIR_64): $(ROOT_SBBR_MISC_DIR_32)
	-$(INS.dir)

$(ROOT_SBBR_MOD_DIR)/%: $(OBJS_DIR)/% $(ROOT_SBBR_MOD_DIR) FRC
	$(INS.file)

$(ROOT_SBBR_MISC_DIR)/%: $(OBJS_DIR)/% $(ROOT_SBBR_MISC_DIR) FRC
	$(INS.file)

$(ROOT_SBBR_DRV_DIR)/%: $(OBJS_DIR)/% $(ROOT_SBBR_DRV_DIR) FRC
	$(INS.file)

$(USR_SBBR_DIR):	$(USR_ARMV8_PLAT_DIR)
	-$(INS.dir)

$(USR_SBBR_INC_DIR):	$(USR_SBBR_DIR)
	-$(INS.slink4)

$(USR_SBBR_ISYS_DIR):	$(USR_SBBR_INC_DIR)
	-$(INS.dir)

$(USR_SBBR_SBIN_DIR):	$(USR_SBBR_DIR)
	-$(INS.slink5)

$(USR_SBBR_LIB_DIR):	$(USR_SBBR_DIR)
	-$(INS.dir)

$(LINKED_PLATFORMS:%=$(USR_PLAT_DIR)/%): $(USR_PLAT_DIR)
	$(INS.slink3)
$(PPLINKED_PLATFORMS:%=$(ROOT_PLAT_DIR)/%): $(ROOT_PLAT_DIR)
	$(INS.slink3)

$(ROOT_SBBR_KERN_DIR)/%:	$(OBJS_DIR)/% $(ROOT_SBBR_KERN_DIR) FRC
	$(INS.file)

#
#	Include common targets.
#
include $(UTSBASE)/$(PLATFORM)/sbbr/Makefile.rules
include $(UTSBASE)/$(PLATFORM)/Makefile.targ
