#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 1999, 2010, Oracle and/or its affiliates. All rights reserved.
# Copyright 2019 Joyent, Inc.
# Copyright 2018 Nexenta Systems, Inc.
# Copyright 2019 Peter Tribble.
#

#
#	This Makefile defines all file modules and build rules for the
# directory uts/aarch64 and its children. These are the source files which
# are specific to aarch64 processor architectures.
#

#
#	Core (unix) objects
#
CORE_OBJS +=			\
	arch_kdi.o		\
	bcmp.o			\
	bcopy.o			\
	bitmap_arch.o		\
	bzero.o			\
	cpuid.o			\
	ddi_arch.o		\
	ip_ocsum.o		\
	memchr.o		\
	memcmp.o		\
	memcpy.o		\
	memmove.o		\
	memset.o		\
	ovbcopy.o		\
	polled_io.o		\
	sendsig.o		\
	strlen.o		\
	sundep.o		\
	vpanic.o		\
	x_call.o

#
#	Generic-unix Module
#
GENUNIX_OBJS +=		\
	archdep.o	\
	syscall.o	\
	fpu.o		\
	float.o		\
	getcontext.o	\
	install_utrap.o	\
	kdi_svc.o	\
	popcountdi2.o

#
#	PROM Routines,
#
#	XXXARM: called earlier in boot than usual and so in 'unix'
#	it'd be nice if they weren't, but I doubt that's possible right now.
#
#	On the other hand, on systems with some form of actual monitor, this
#	is usefully platform-specific
#
CORE_OBJS +=			\
	prom_node.o		\
	prom_init.o		\
	prom_env.o		\
	prom_printf.o		\
	prom_putchar.o		\
	prom_getchar.o		\
	prom_version.o		\
	prom_reboot.o		\
	prom_panic.o		\
	prom_enter.o		\
	prom_exit.o		\
	prom_prop.o

#
#	When building unix for FDT, include these objects.
#
CORE_OBJS_FDT +=		\
	fdt.o			\
	fdt_ro.o		\
	fdt_wip.o		\
	fdt_sw.o		\
	fdt_rw.o		\
	fdt_strerror.o		\
	fdt_empty_tree.o	\
	fdt_addresses.o		\
	fdt_overlay.o		\
	fdt_check.o

#
#	file system modules
#
CORE_OBJS +=		\
	prmachdep.o

#
#	ZFS file system module
#
ZFS_OBJS +=		\
	spa_boot.o

#
#	Decompression code
#
CORE_OBJS += decompress.o

#
#	Microcode utilities
#
#CORE_OBJS += ucode_utils.o

ASSYM_DEPS +=		\
	float.o

#
#	Driver modules
#
CMLB_OBJS += cmlb.o
SD_OBJS += sd.o sd_xbuf.o

STRATEGY_OBJS += strategy.o

DEVFDT_OBJS += devfdt.o

PCIERC_OBJS +=		\
	pci_boot.o	\
	pci_common.o	\
	pci_kstats.o	\
	pci_tools.o	\
	pcierc.o

ECAM_OBJS += ecam.o

#
#	Kernel linker
#
KRTLD_OBJS +=			\
	bootfsops.o		\
	bootrd.o		\
	bootrd_cpio.o		\
	doreloc.o		\
	hsfs.o			\
	kobj_convrelstr.o	\
	kobj_isa.o		\
	kobj_reloc.o		\
	ufsops.o

#
#	misc. modules
#
ACPICA_OBJS +=			\
	dmbuffer.o dmcstyle.o dmdeferred.o dmnames.o dmopcode.o \
	dmresrc.o dmresrcl.o dmresrcl2.o dmresrcs.o dmutils.o \
	dmwalk.o \
	\
	dsargs.o dscontrol.o dsdebug.o dsfield.o dsinit.o \
	dsmethod.o dsmthdat.o dsobject.o dsopcode.o dsutils.o \
	dswexec.o dswload.o dswload2.o dswscope.o dswstate.o \
	dspkginit.o \
	\
	evevent.o evglock.o evgpe.o evgpeblk.o evgpeinit.o \
	evgpeutil.o evhandler.o evmisc.o evregion.o evrgnini.o \
	evsci.o evxface.o evxfevnt.o evxfgpe.o evxfregn.o \
	\
	exconcat.o exconfig.o exconvrt.o excreate.o exdebug.o \
	exdump.o exfield.o exfldio.o exmisc.o exmutex.o exnames.o \
	exoparg1.o exoparg2.o exoparg3.o exoparg6.o exprep.o \
	exregion.o exresnte.o exresolv.o exresop.o exstore.o \
	exstoren.o exstorob.o exsystem.o extrace.o exutils.o \
	\
	hwacpi.o hwesleep.o hwgpe.o hwpci.o hwregs.o hwsleep.o \
	hwtimer.o hwvalid.o hwxface.o hwxfsleep.o \
	\
	psargs.o psloop.o psobject.o psopcode.o psopinfo.o \
	psparse.o psscope.o pstree.o psutils.o pswalk.o psxface.o \
	\
	nsaccess.o nsalloc.o nsarguments.o nsconvert.o nsdump.o \
	nsdumpdv.o nseval.o nsinit.o nsload.o nsnames.o nsobject.o \
	nsparse.o nspredef.o nsprepkg.o nsrepair.o nsrepair2.o \
	nssearch.o nsutils.o nswalk.o nsxfeval.o nsxfname.o \
	nsxfobj.o \
	\
	rsaddr.o rscalc.o rscreate.o rsdump.o rsdumpinfo.o \
	rsinfo.o rsio.o rsirq.o rslist.o rsmemory.o rsmisc.o \
	rsserial.o rsutils.o rsxface.o \
	\
	tbdata.o tbfadt.o tbfind.o tbinstal.o tbprint.o tbutils.o \
	tbxface.o tbxfload.o tbxfroot.o \
	\
	utaddress.o utalloc.o utascii.o utbuffer.o utcache.o \
	utclib.o utcopy.o utdebug.o utdecode.o utdelete.o \
	uterror.o uteval.o utexcep.o utglobal.o uthex.o utids.o \
	utinit.o utlock.o utmath.o utmisc.o utmutex.o utnonansi.o \
	utobject.o utosi.o utownerid.o utpredef.o utresrc.o \
	utstate.o utstring.o uttrack.o utuuid.o utxface.o \
	utxferror.o utxfinit.o utxfmutex.o utresdecode.o \
	utstrsuppt.o utstrtoul64.o \
	\
	acpica.o ahids.o \
	osl.o osl_pci.o osl_ffh.o ffh.o

#
#	special files
#
MODSTUB_OBJ +=		\
	modstubs.o

INC_PATH	+= -I$(UTSBASE)/aarch64
